// examples/react19/src/App.tsx
import { useState } from 'react';
import hotLogo from '@hotosm/ui/theme/logo.png';

import '@hotosm/ui/dist/style.css';
import '@hotosm/ui/dist/components.js';

const App = () => {
  const [undoCount, setUndoCount] = useState(0);
  const [redoCount, setRedoCount] = useState(0);
  const [boldCount, setBoldCount] = useState(0);
  const [italicCount, setItalicCount] = useState(0);
  const [underlineCount, setUnderlineCount] = useState(0);
  const [leftAlignCount, setLeftAlignCount] = useState(0);
  const [centerAlignCount, setCenterAlignCount] = useState(0);
  const [rightAlignCount, setRightAlignCount] = useState(0);

  const incrementCounter = (type) => {
    switch (type) {
      case 'undo':
        setUndoCount((prevCount) => prevCount + 1);
        break;
      case 'redo':
        setRedoCount((prevCount) => prevCount + 1);
        break;
      case 'bold':
        setBoldCount((prevCount) => prevCount + 1);
        break;
      case 'italic':
        setItalicCount((prevCount) => prevCount + 1);
        break;
      case 'underline':
        setUnderlineCount((prevCount) => prevCount + 1);
        break;
      case 'leftAlign':
        setLeftAlignCount((prevCount) => prevCount + 1);
        break;
      case 'centerAlign':
        setCenterAlignCount((prevCount) => prevCount + 1);
        break;
      case 'rightAlign':
        setRightAlignCount((prevCount) => prevCount + 1);
        break;
      default:
        break;
    }
  };

  return (
    <main>
      <div>
        <a href="https://hotosm.org" target="_blank" rel="noreferrer">
          <img src={hotLogo} className="logo" alt="HOT Logo" />
        </a>
      </div>

      <h2>HOTOSM UI React Example</h2>

      <hot-toolbar
        tooltipPosition="bottom"
        onundo={() => { incrementCounter('undo'); }}
        onredo={() => { incrementCounter('redo'); }}
        onbold={() => { incrementCounter('bold'); }}
        onitalic={() => { incrementCounter('italic'); }}
        onunderline={() => { incrementCounter('underline'); }}
        onleftalign={() => { incrementCounter('leftAlign'); }}
        oncenteralign={() => { incrementCounter('centerAlign'); }}
        onrightalign={() => { incrementCounter('rightAlign'); }}
      ></hot-toolbar>

      <p>Undo: {undoCount}</p>
      <p>Redo: {redoCount}</p>
      <p>Bold: {boldCount}</p>
      <p>Italic: {italicCount}</p>
      <p>Underline: {underlineCount}</p>
      <p>Justify Left: {leftAlignCount}</p>
      <p>Justify Center: {centerAlignCount}</p>
      <p>Justify Right: {rightAlignCount}</p>
    </main>
  );
};

export default App;

// examples/svelte/src/App.svelte
<script type="module" lang="ts">
  import '@hotosm/ui/theme/hot.css';
  import '@hotosm/ui/components/Toolbar';
  import hotLogo from '@hotosm/ui/theme/logo.png';
  import { onMount } from 'svelte';

  let undoCount = 0;
  let redoCount = 0;
  let boldCount = 0;
  let italicCount = 0;
  let underlineCount = 0;
  let leftAlignCount = 0;
  let centerAlignCount = 0;
  let rightAlignCount = 0;

  const undoClick = () => {
    undoCount++;
  };

  const redoClick = () => {
    redoCount++;
  };

  const boldClick = () => {
    boldCount++;
  };

  const italicClick = () => {
    italicCount++;
  };

  const underlineClick = () => {
    underlineCount++;
  };

  const leftAlignClick = () => {
    leftAlignCount++;
  };

  const centerAlignClick = () => {
    centerAlignCount++;
  };

  const rightAlignClick = () => {
    rightAlignCount++;
  };

  // Reset values when component mounts
  onMount(() => {
    undoCount = 0;
    redoCount = 0;
    boldCount = 0;
    italicCount = 0;
    underlineCount = 0;
    leftAlignCount = 0;
    centerAlignCount = 0;
    rightAlignCount = 0;
  });
</script>

<main>
  <div>
    <a href="https://hotosm.org" target="_blank" rel="noreferrer">
      <img src={hotLogo} class="logo" alt="HOT Logo" />
    </a>
  </div>

  <h2>HOTOSM UI Svelte Example</h2>

  <hot-toolbar
    tooltip-position="bottom"
    on:hot-undo-click={undoClick}
    on:hot-redo-click={redoClick}
    on:hot-bold-click={boldClick}
    on:hot-italic-click={italicClick}
    on:hot-underline-click={underlineClick}
    on:hot-leftalign-click={leftAlignClick}
    on:hot-centeralign-click={centerAlignClick}
    on:hot-rightalign-click={rightAlignClick}
  ></hot-toolbar>

  <p>Undo: {undoCount}</p>
  <p>Redo: {redoCount}</p>
  <p>Bold: {boldCount}</p>
  <p>Italic: {italicCount}</p>
  <p>Underline: {underlineCount}</p>
  <p>Justify Left: {leftAlignCount}</p>
  <p>Justify Center: {centerAlignCount}</p>
  <p>Justify Right: {rightAlignCount}</p>

</main>

<style>
  .logo {
    height: 4em;
    padding: 1em;
    will-change: filter;
    transition: filter 300ms;
  }

  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }

  p {
    font-size: 1.2em;
    margin-top: 1em;
  }
</style>
